// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entities "github.com/OmarAouini/golang-api-starter/entities"
	mock "github.com/stretchr/testify/mock"
)

// CompanyStore is an autogenerated mock type for the CompanyStore type
type CompanyStore struct {
	mock.Mock
}

// All provides a mock function with given fields:
func (_m *CompanyStore) All() (*[]entities.Company, error) {
	ret := _m.Called()

	var r0 *[]entities.Company
	if rf, ok := ret.Get(0).(func() *[]entities.Company); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.Company)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: new
func (_m *CompanyStore) Create(new *entities.Company) error {
	ret := _m.Called(new)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Company) error); ok {
		r0 = rf(new)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *CompanyStore) Get(id int) (*entities.Company, error) {
	ret := _m.Called(id)

	var r0 *entities.Company
	if rf, ok := ret.Get(0).(func(int) *entities.Company); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Company)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: name
func (_m *CompanyStore) GetByName(name string) (*entities.Company, error) {
	ret := _m.Called(name)

	var r0 *entities.Company
	if rf, ok := ret.Get(0).(func(string) *entities.Company); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Company)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
